version: '3.9'

services:
  app:
    container_name: flask_portfolio_app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '5000:5000'
    env_file:
      - compose.env
    command: "flask run --port='5000'"
  flask_db:
    container_name: flask_db
    image: mariadb
    ports: 
      - "3306:3306"
    env_file:
      - db.env
    volumes:
      - flask_data:/var/lib/mysql
volumes:
  flask_data: